import * as THREE from "three";
import { WGSLNodeBuilder, StorageInstancedBufferAttribute } from "three/webgpu";
import { context } from "three/tsl";
import { createTSLParticleMaterial } from "./public/lib/three-particles-webgpu.esm.js";
const stub = { isNodeManager: true, contextNode: context(), library: { fromMaterial: (m) => m }, constants: [], debug: { diagnostics: { keywords: [] }, onNodeBuilderCreated: null }, backend: { isBackend: true, utils: { getTextureSampleData: () => ({ primarySamples: 1, imageSampleCount: 1 }) } }, hasFeature: () => true, getRenderTargetTarget: () => ({}), getRenderTarget: () => null, xr: { enabled: false }, lighting: { enabled: false }, info: { render: {} } };
const tex = new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1); tex.needsUpdate = true;
const shared = { elapsed:{value:0}, viewportHeight:{value:720}, cameraNearFar:{value:new THREE.Vector2(0.1,1000)}, map:{value:tex}, fps:{value:30}, useFPSForFrameIndex:{value:true}, tiles:{value:new THREE.Vector2(4,4)}, discardBackgroundColor:{value:true}, backgroundColor:{value:new THREE.Color(0,0,0)}, backgroundColorTolerance:{value:0.1}, softParticlesEnabled:{value:false}, softParticlesIntensity:{value:1}, sceneDepthTexture:{value:null} };
const N=8;
const gi = new THREE.InstancedBufferGeometry();
gi.setAttribute('position', new THREE.BufferAttribute(new Float32Array([-.5,-.5,0,.5,-.5,0,.5,.5,0,-.5,.5,0]),3));
gi.setIndex(new THREE.BufferAttribute(new Uint16Array([0,1,2,0,2,3]),1));
gi.instanceCount = N;
["instanceOffset","instanceColor","instanceParticleState","instanceStartValues"].forEach(n=>gi.setAttribute(n,new StorageInstancedBufferAttribute(new Float32Array(N*4).fill(1),4)));
const material = createTSLParticleMaterial("INSTANCED", shared, { transparent:true, blending:2, depthTest:true, depthWrite:false }, true);
const obj = new THREE.Mesh(gi, material);
const b = new WGSLNodeBuilder(obj, stub); b.object=obj; b.material=material; b.geometry=gi; b.scene=new THREE.Scene(); b.camera=new THREE.PerspectiveCamera(60,1,.1,1000);
const p1 = Object.getPrototypeOf(b), p2 = Object.getPrototypeOf(p1);
console.log("L2:", Object.getOwnPropertyNames(p2).join(","));
let msgs = []; const oe = console.error;
const cap = () => { msgs = []; console.error = (...a)=>msgs.push(String(a[0])); };
const stop = () => { console.error = oe; return msgs.slice(); };
cap(); try { b.stage("vertex"); } catch(e) { oe(" err", e.message); }
oe("[stage vertex] ", stop());
cap(); b.build(); oe("[build] ", stop());